### ISSUE TITLE
현재 작성하는 문제의 코드를 간단하게 저장할수 있을까요?

### ISSUE THREAD

**Issue by inmare** [wildcatco/boj-helper#6]
지금 현재 풀고 있는 문제의 코드를 localStorage등에 간단하게 저장할 수 있으면 좋을것 같아요.
휴대폰에서 풀고 있는데 새로 고침 될때마다 푼거1 사라지니까 불편하더라고요.
만드신 사이트 잘 사용하고 있습니다. 감사합니다.

**Comment by wildcatco** [comment]
@inmare 좋은 기능인거 같네요 5초마다 현재 작성중인 코드를 로컬스토리지에 저장하는 기능을 추가했습니다~

https://github.com/wildcatco/boj-helper/commit/4c790fcc2787805a182ef614cf03f1ad7a873203
