### ISSUE TITLE
javascript 출력에 대한 질문

### ISSUE THREAD

**Issue by parkdh9018** [wildcatco/boj-helper#7]
![image](https://github.com/user-attachments/assets/f007091c-b608-4883-8db1-f40d90bcdeb7)
![image](https://github.com/user-attachments/assets/f174a188-2d1a-4901-8355-0c40dbb1edd7)

2차원 배열을 출력하게 되면 flat을 거쳐서 나오는 것 같은데, 의도된 것 일까요?

**Comment by wildcatco** [comment]
@parkdh9018 객체도 올바르게 출력되도록 수정했습니다! https://github.com/wildcatco/boj-helper/commit/7d5741f42e70c574a9a7e6f28d17b2b55e812ff5

![image](https://github.com/user-attachments/assets/e4cfb393-eb98-4ab1-a9e2-9593b0c38742)
