### ISSUE TITLE
예제 입력, 출력의 이미지

### ISSUE THREAD

**Issue by parkdh9018** [wildcatco/boj-helper#8]
가끔씩 예제에도 이미지가 들어있는 문제가 있는데, 이것까지 보였으면 좋겠습니다.
아래는 27942번 입니다.
![image](https://github.com/user-attachments/assets/8eef0ba6-8d17-4b0f-a090-f10ace2ec1b4)

**Comment by wildcatco** [comment]
@parkdh9018 예제에도 이미지가 있는게 있군요. 구현해보겠습니다

**Comment by wildcatco** [comment]
@parkdh9018 각 예제에 대한 설명도 보여주도록 수정했습니다!

<img src="https://github.com/user-attachments/assets/f59712ef-227e-481e-9f00-8ef262731dab" width="300">
<br>
<img src="https://github.com/user-attachments/assets/d21f0bee-7aa8-4150-b888-1adddc918115" width="300">
